version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:11.0

    steps:
      - checkout

      - run:
          name: Build
          command: mvn -B -DskipTests clean package

      - run:
          name: Test with JaCoCo
          command: mvn test

      - run:
          name: Generate Coverage Report
          command: mvn jacoco:report

  deploy-coverage:
    docker:
      - image: cimg/openjdk:11.0

    steps:
      - checkout

      - run:
          name: List Coverage Files
          command: ls -R target/site/jacoco


      # Publiez le rapport de couverture vers Codecov
      - codecov/upload:
          file: target/site/jacoco/jacoco.xml
          token: CODECOV_TOKEN

workflows:
  sample:
    jobs:
      - build-and-test
      - deploy-coverage:
          requires:
            - build-and-test
