version: 2.1

# Intégration de l'orb Codecov pour simplifier le processus de publication de la couverture
orbs:
  codecov: codecov/codecov@4.0.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:11.0

    steps:
      - checkout

      # Étape de compilation du projet
      - run:
          name: Build
          command: mvn -B -DskipTests clean package

      # Exécution des tests pour générer la couverture
      - run:
          name: Test with JaCoCo
          command: mvn test

      # Générez le rapport de couverture avec JaCoCo
      - run:
          name: Generate Coverage Report
          command: mvn jacoco:report

      # Exécutez Checkstyle pour vérifier le style du code
      - run:
          name: Run Checkstyle
          command: mvn checkstyle:check

      # Publiez le rapport de couverture sur Codecov
      - codecov/upload:
          file: target/site/jacoco/jacoco.xml
          token: CODECOV_TOKEN

  javadoc:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Generate Javadoc
          command: mvn javadoc:javadoc
      - run:
          name: Copy Javadoc to Temp Directory
          command: cp -r target/site/apidocs ./javadoc-temp
      - persist_to_workspace:
          root: .
          paths:
            - javadoc-temp

  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - attach_workspace:
          at: /workspace
      - run:
          name: Verify Javadoc Directory
          command: |
            if [ ! -d "/workspace/javadoc-temp" ]; then
              echo "Javadoc directory does not exist"
              exit 1
            fi
      - run:
          name: Configure Git
          command: |
            git config --global user.email "ci-build@example.com"
            git config --global user.name "ci-build"
      - run:
          name: Deploy Javadoc to gh-pages
          command: |
            mkdir gh-pages-temp
            cp -r /workspace/javadoc-temp/* gh-pages-temp/
            cd gh-pages-temp
            git init
            git checkout --orphan gh-pages
            touch .nojekyll
            git add .
            git commit -m "[skip ci] Deploy Javadoc to gh-pages"
            git remote add origin https://github.com/Anthony-genti/ceri-m1-techniques-de-test.git
            git push -f origin gh-pages

workflows:
  sample:
    jobs:
      - build-and-test
      - javadoc:
          requires:
            - build-and-test
      - deploy:
          requires:
            - javadoc
          filters:
            branches:
              only: master
