version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:11.0

    steps:
      - checkout

      - run:
          name: Build
          command: mvn -B -DskipTests clean package

      # Exécution des tests et génération du rapport de couverture en un seul passage
      - run:
          name: Test and Generate Coverage Report
          command: mvn verify

  deploy-coverage:
    docker:
      - image: cimg/openjdk:11.0

    steps:
      - checkout

      - run:
          name: Check Coverage Files
          command: ls -R target/site/jacoco || echo "Coverage files not found"

      # Publication du rapport de couverture vers Codecov
      - codecov/upload:
          file: target/site/jacoco/jacoco.xml
          token: CODECOV_TOKEN

workflows:
  sample:
    jobs:
      - build-and-test
      - deploy-coverage:
          requires:
            - build-and-test
