# Utilisez la dernière version 2.1 du moteur de pipeline CircleCI
version: 2.1

# Importer les orbs nécessaires
orbs:
  codecov: codecov/codecov@4.0.1

# Définir un job pour build et tester
jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:11.0

    steps:
      - checkout

      # Build le projet Maven
      - run:
          name: Build
          command: mvn -B -DskipTests clean package

      # Exécuter les tests et générer un rapport de couverture
      - run:
          name: Test
          command: mvn test

      # Étape pour envoyer les résultats de couverture à Codecov
      - codecov/upload:
          file: target/site/jacoco/jacoco.xml # Assurez-vous que le rapport de couverture est généré ici
          flags: unittests # Vous pouvez ajouter des flags si nécessaire

# Définir les workflows
workflows:
  version: 2
  sample:
    jobs:
      - build-and-test
