version: 2.1

# Intégration de l'orb Codecov pour simplifier le processus de publication de la couverture
orbs:
  codecov: codecov/codecov@4.0.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:11.0

    steps:
      - checkout

      # Étape de compilation du projet
      - run:
          name: Build
          command: mvn -B -DskipTests clean package

      # Exécution des tests pour générer la couverture
      - run:
          name: Test with JaCoCo
          command: mvn test

      # Générez le rapport de couverture avec JaCoCo
      - run:
          name: Generate Coverage Report
          command: mvn jacoco:report

      # Exécutez Checkstyle pour vérifier le style du code
      - run:
          name: Run Checkstyle
          command: mvn checkstyle:check

      # Publiez le rapport de couverture sur Codecov
      - codecov/upload:
          file: target/site/jacoco/jacoco.xml
          token: CODECOV_TOKEN

  javadoc:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Generate Javadoc
          command: mvn javadoc:javadoc
      - run:
          name: Create Site Directory
          command: mkdir -p target/site/apidocs
      - run:
          name: List Target Directory
          command: ls -la target
      - run:
          name: List Javadoc Directory
          command: ls -la target/site
      - persist_to_workspace:
          root: .
          paths:
            - target/site/apidocs

  deploy:
    docker:
      - image: cimg/node:14.14
    steps:
      - checkout
      - attach_workspace:
          at: /workspace
      - run:
          name: Install gh-pages
          command: npm install -g gh-pages
      - run:
          name: Deploy Javadoc to gh-pages
          command: |
            git config --global user.email "ci-build@example.com"
            git config --global user.name "ci-build"
            touch /workspace/target/site/apidocs/.nojekyll
            gh-pages --dotfiles --message "[skip ci] Updates" --dist /workspace/target/site/apidocs

workflows:
  sample:
    jobs:
      - build-and-test
      - javadoc:
          requires:
            - build-and-test
      - deploy:
          requires:
            - javadoc
          filters:
            branches:
              only: master